### ISSUE TITLE
Bug where passives and actives aren't removed

### ISSUE THREAD

**Issue by PROMETHIA-27** [1TeaL/Shigaraki#1]
When you capture a passive quirk and assign it to an active skill slot, it can't be removed, only (maybe) overwritten by certain other quirks. Likewise when you capture an active quirk and assign it to a passive slot, it can't be removed, only maybe overwritten. I tracked it to this part of the code: https://github.com/1TeaL/Shigaraki/blob/main/ShiggyVS/ShiggyMod/Modules/Survivors/ShiggyController.cs#L1945

The remove functions attempt to only remove passive abilities from passive slots and actives from actives. I think this can just be changed to be one function that removes all quirks from whatever slot is being removed from. Hope this helps!

**Comment by 1TeaL** [comment]
Ah yes, this was an oversight and should have been changed. Thanks for catching this. I'm in the middle of refactoring the skill code for 2.0 so I might just release it together. I'll see how it is though. Should be an easy fix, thanks!
