### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by MrShadow802** [1TeaL/Shigaraki#2]
Is it normal that if you steal the element of an void enemy that the games breaks?
How do you get the Synergie for his spezial skill i cant copy it from deku?

Ps:sorry for spelling

**Comment by 1TeaL** [comment]
Could you let me know which void enemy? Also if you have a log file could you attach it?
And yes Deku not copying is an issue I'll fix in the next update.

**Comment by MrShadow802** [comment]
Because of the void essence the game probaly crashed because of the multiplayer.
But the the qirks that can stak the stacks wont go away for some reason and stay for the rest of the stage and not like the qirks says like one each second.

**Comment by 1TeaL** [comment]
Hm I see omniboost- still an issue. I'll aim to fix it.
What's the void essence? Like the small void things?

**Comment by 1TeaL** [comment]
A new update to fix the Deku OFA and also a new method to get OFA has been added. 
I'm not sure what the void essence fix would be so I'll be fixing this when I get more data.

**Comment by MrShadow802** [comment]
Thanks for the update. The Ofa Is fixed, the Void Essence is normal ther is
nothing wrong with that im sorry that was my mistake, the stack from
abilitis like omnibosst still breaks i will try to find out when it breaks
and the jump pads dont work right they just push him in a random direktion.

Am Di., 20. Juni 2023 um 10:50 Uhr schrieb 1TeaL ***@***.***>:
