### ISSUE TITLE
passives staying?

### ISSUE THREAD

**Issue by zazule** [1TeaL/Shigaraki#4]
hello,
ive only just recently downloaded this mod and i noticed when i get the wisp passive and beetle passive they combine i get all 3 passives the one fomr wisp and beetle and the 1.3x for attacks one. However, if i was to get rid of the quirks by replacving it with say a golem beam the passive buffs stay on my charter. should they? 

so TLDR: my passives are staying even when i get rid of the quirk is this normal?

**Comment by 1TeaL** [comment]
Hmm shouldn't be happening. 
Do you have a log file?

**Comment by zazule** [comment]
ah sorry i figured out what was happening im not sure how to get a log file im sorry new to this but whever i take na ability passive it resets when i go to the next stage so i wont have the passives but it seems some synergies arnt working right the wisp +beetle passive shoudnt be Omniboost but it dose

**Comment by zazule** [comment]
for example ive attached 2 screen shots 1 having the ombi boost when i think i need the double time form beetle+wisp ability then combine that with the commando and soul probe right? 
[](url)
and the 2nd is when ive removed the ability with the golem blast one and i still have the 2 passives:

![362412324_795962908680113_5376177448935800691_n](https://github.com/1TeaL/Shigaraki/assets/140408514/ea83d0bd-0105-40b2-96dd-60dfaeb3530a)


![362467704_312529057876617_7058944958027914787_n](https://github.com/1TeaL/Shigaraki/assets/140408514/d268c0d4-412d-425b-8fd5-ddf0ea04e41d)

**Comment by 1TeaL** [comment]
In r2modman, In the settings there's a profile location folder, click that.
Then inside I think you click into the bepinex folder and you'll see a logoutput.log file.
Also what's your modlist?

**Comment by zazule** [comment]
very sorry for the wait ill gwt thta for you now.

[LogOutput.log](https://github.com/1TeaL/Shigaraki/files/12152456/LogOutput.log)

mod list: BepInEx_GUI by RiskofThunder

FixPluginTypesSerialization by RiskofThunder

RoR2BepInExPack by RiskofThunder

BepInExPack by bbepis

BetterUI by XoXFaby

HookGenPatcher by RiskofThunder

R2API_ContentManagement by RiskofThunder

R2API_Core by RiskofThunder

R2API_Prefab by RiskofThunder

R2API_DamageType by RiskofThunder

R2API_Director by RiskofThunder

R2API_Language by RiskofThunder

R2API_RecalculateStats by RiskofThunder

R2API_Unlockable by RiskofThunder

Enforcer by EnforcerGang

LoLItems by Debo

ScrollableLobbyUI by KingEnderBrine

R2API_Networking by RiskofThunder

R2API_Sound by RiskofThunder

ExtraSkillSlots by KingEnderBrine

DekuMod by TeaL

R2API_Skins by RiskofThunder

R2API_SceneAsset by RiskofThunder

R2API_Elites by RiskofThunder

R2API_Items by RiskofThunder

R2API_Loadout by RiskofThunder

R2API_TempVisualEffect by RiskofThunder

R2API_ArtifactCode by RiskofThunder

R2API_CommandHelper by RiskofThunder

R2API_Deployable by RiskofThunder

R2API_Dot by RiskofThunder

R2API_LobbyConfig by RiskofThunder

R2API_Orb by RiskofThunder

R2API_Difficulty by RiskofThunder

R2API by tristanmcpherson

PaladinMod by Paladin_Alliance

Gunslinger by Dragonyck

AssassinMod by HasteReapr

Aatrox by Team_Pepega

ShigarakiMod by TeaL

**Comment by zazule** [comment]
very sorry about this

**Comment by 1TeaL** [comment]
Hey it's a bit weird it seems quite short, the log contains the previous game so if you get a game where this happens could you then get the log after? Thanks

**Comment by zazule** [comment]
[LogOutput.log](https://github.com/1TeaL/Shigaraki/files/12159700/LogOutput.log)

i think thats right i clicked on it just to check i got the abilitys again the beetle then the wisp geting omni boost.
Had some trouble clicking F on a lemarian to cancle the ability then remeberd i could just click V to get rid and passives but was still there after geting rid of them

sorry for all the long qwaiting i live in the uk and it was nearll 11pm last night
